// Typelizer digest 2b9916ab9509d19ba713fe5ec05db93b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { User } from './'

type Account = User & {
  email: string
  social_login: boolean
}

export default Account
