// Typelizer digest ea18e4c150e4df08ed5a3ebf092f664e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface ErrorMap {
  title: string
  detail: string
  source?: string
}

export default ErrorMap
