// Typelizer digest 3925d82bb93ee4bdcfacb0ed4a0d572f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { User } from '~/types'

type Account = User & {
  email: string
  social_login: boolean
}

export default Account
