// Typelizer digest 4f45779cf3569d3f165f50ca39a828c1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { User } from '@/types'

type Account = User & {
  email: string
  social_login: boolean
}

export default Account
