// Typelizer digest dddf0368c991e51c3dc0aafb110fb5d5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface Comment {
  id: number
  user_id: number
  frame_id: number
  body: string | null
  user_name: string
  user_image_url: string
  created_at: string
  updated_at: string
}

export default Comment
