// Typelizer digest c315da98cb9c860493e37b70020c2b83
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface Comment {
  id: number
  user_id: number
  frame_id: number
  body: string | null
  user_name: string
  user_image_url: string
  created_at: string
  updated_at: string
}

export default Comment
