// Typelizer digest 3ece56d0cb3be5e89bf867b575e89b5e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface ErrorMap {
  errors: Record<string, string[]>
}

export default ErrorMap
