// Typelizer digest 0409018c6ca3ceda146bf2b10b4a8fe0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface ErrorMap {
  title: string
  errors: string[]
  source?: string
}

export default ErrorMap
