// Typelizer digest 8560475f114a2cd7370221246dd16e06
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface ErrorMessages {
  errors: Record<string, string[]>
}

export default ErrorMessages
