// Typelizer digest 0ee7cfbae0f340104529e960ad8c41d2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface ErrorMap {
  title: string
  errors: string[]
  source?: string
}

export default ErrorMap
