// Typelizer digest 12de0f040c2de6bba49fa8805f98c8b7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface ErrorMessages {
  errors: Record<string, string[]>
}

export default ErrorMessages
