// Typelizer digest 5e00e2e376bdd840b1b480c27e359364
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface User {
  id: number
  name: string
  image_thumb_url: string
  image_one_url: string
  image_three_url: string
}

export default User
