// Typelizer digest da8a2ed0aef87e782afad9354a4da562
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface User {
  id: number
  name: string
  image_thumb_url: string
  image_one_url: string
  image_three_url: string
}

export default User
