// Typelizer digest ebef9ba2735af1dfa2f80043ad7261cb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface User {
  id: number
  name: string
  image_thumb_url: string
  image_one_url: string
  image_three_url: string
}

export default User
